# Generated by Django 5.2.4 on 2025-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='crowd_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiting_time',
            field=models.PositiveIntegerField(default=0, help_text='Enter waiting time in minutes'),
        ),
    ]
